#ifndef __DTS_AX650_OPTEE_DEFINE_H
#define __DTS_AX650_OPTEE_DEFINE_H

#define OPTEE_BOOT
#ifdef OPTEE_BOOT
#define OPTEE_RESERVED_START_HI 0x1
#define OPTEE_RESERVED_START_LO 0x34000000
#define OPTEE_RESERVED_SIZE_HI 0x0
#define OPTEE_RESERVED_SIZE_LO 0x2000000
#endif

#endif /* __DTS_AX650_OPTEE_DEFINE_H */
